spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/circuitqa?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  #    password: windway!@#$
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.sysu.circuitQA.pojo
server:
  port: 8080
  max-http-header-size: 1024000   # 请求头太大报错

